# Generated by Django 4.2.7 on 2025-04-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_employerprofile_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
